---
title: "Ćwiczenie 1.7"
author: "Kacper Telesz"
format: html
---

## Przygotowanie zbioru danych 'airquality':

```{r}

colnames(airquality) <- tolower(colnames(airquality)) # Zmiana nazw kolumn na małe litery

air <- 
  airquality |> 
  as_tibble() |> # konwersja na tibble
  na.omit() |>  # usuwamy brakujące dane
  select(-day) |> # Usunięcie kolumny 'day'
  mutate(month = factor(month)) # Zmienna 'month' zostaje przekształcona na zmienną kategoryczną (factor)

str(air) # Sprawdzenie struktury danych
```
## Analiza danych 

```{r}

#install.packages("GGally")
library(GGally)

ggpairs(air[4]) # wizualizacja
#ggally_autopoint(air)

air %>%
  ggplot(aes(
    x = solar.r,
    y = ozone,
    col = month,
    group = month
  )) +
  geom_point() +
  geom_smooth(method = lm, se = F) +
  scale_color_viridis_d(option = "C", end = .9)
```


## Tworzenie modelu szacującego zawartość ozonu w atmosferze

```{r}

ozone ~ solar.r * wind * temp

linear_reg()

lm_mod <- 
  linear_reg() |> 
  set_engine("lm")

lm_fit <-  
  lm_mod |>
  fit(ozone ~ solar.r * wind * temp, data = air)
lm_fit  

lm_fit$fit |> summary()
lm_fit |> tidy()
lm_fit |> tidy(conf.int = T)
```

```{r}

lm_fit |> 
  tidy() |> 
  dwplot(vline = geom_vline(xintercept = 0, color = "grey50", linetype = 2), 
         dot_args = list(size = 2, color = "black"), 
         whisker_args = list(color = "black")) +
  theme_bw()

```
Wnioski: największy wpływ na zawartość o3 w powietrzu ma wiatr, pójźniej temperatura a najmniejszy wpływ ma promieniowanie słoneczne.

## Prognozowanie o3 

```{r}
new_points <- expand.grid(solar.r = seq(300,400,10), 
                          wind = seq(5,20,5),
                          temp = seq(60,90,10))
```

```{r}
# Prognoza średniej wartości
mean_pred <- predict(object = lm_fit, new_data = new_points)

# Prognoza przedizału ufności
conf_pred <- predict(object = lm_fit, new_data = new_points, type = "conf_int")

# Łączenie danych
lm_pred <- 
  new_points |> 
  bind_cols(mean_pred) |> 
  bind_cols(conf_pred)

# WYkres danych

lm_pred |>
  ggplot(aes(x = temp,
             y = .pred)) +
  geom_point() +
  geom_errorbar(aes(ymin = .pred_lower,
                    ymax = .pred_upper),
                width = 0.2) +
  facet_wrap(~ solar.r) +
  theme_bw() +
  labs(y = "air")
```


